FROM centos:7
LABEL maintainer="gvre@gvre.gr"

RUN rpm -Uvh https://dl.fedoraproject.org/pub/epel/epel-release-latest-7.noarch.rpm && \
    rpm -Uvh https://rpms.remirepo.net/enterprise/remi-release-7.rpm && \
    yum-config-manager --enable remi-php73 && \
    yum -y update && \
    yum -y install \
        unzip   \
        make    \
        php-cli \
        php-phpmd-PHP-PMD \
        composer
